Models/Store.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GroceryDash.Models
{
    public class Store: BaseEntity{

        [Key]
        public int id {get; set;}

        [Required]
        public string Name {get; set;}

        [Required]
        public string Address1 {get; set;}

        public string Address2 {get; set;}

        public string City {get; set;}

        public string State {get; set;}

        [Display(Name = "Zip Code")]
        public string Zip {get; set;}

        public string Description {get; set;}

        public DateTime created_at {get; set;}

        public DateTime updated_at {get; set;}

        public int CreatedByUserId {get; set;}
        public User CreatedByUser {get; set;}

        public List<Isle> Isles {get; set;}

        public Store(){
            created_at = DateTime.Now;
            updated_at = DateTime.Now;
            Isles = new List<Isle>();
        }
    }

    public class CreateStoreView: BaseEntity{

        [Required]
        public string Name {get; set;}

        [Required]
        public string Address1 {get; set;}

        public string Address2 {get; set;}

        [Required]
        public string City {get; set;}

        [Required]
        public string State {get; set;}

        [MinLength(5)]
        [Display(Name = "Zip Code")]
        public string Zip {get; set;}

        public string Description {get; set;}

    }
    
}

Controllers/IsleController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Identity;

using GroceryDash.Models;

namespace GroceryDash.Controllers
{
    public class IsleController : Controller
    {
        private GroceryDashContext _context;

        public IsleController(GroceryDashContext context){
            _context = context;
        }

        [HttpGet]
        [Route("createisle/{id}")]
        public IActionResult CreateIsle(int id)
        {
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Categories = _context.ProductCategories;
            ViewBag.StoreId = id;

            return View();
        }

        [HttpGet]
        [Route("updateisle/{id}")]
        public IActionResult UpdateIsle(int id)
        {
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Isle = _context.Isles.Where(isle => isle.id == id).Include(isle => isle.ProductCategories).ThenInclude(ipc => ipc.ProductCategory).SingleOrDefault();
            ViewBag.Categories = _context.ProductCategories;

            return View();
        }

        [HttpPost]
        [Route("createisle/{id}")]
        public IActionResult CreateIsle(CreateIsleView model, int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           ViewBag.Categories = _context.ProductCategories;
           ViewBag.StoreId = id;

            if(ModelState.IsValid){
                Isle newIsle = new Isle{
                    Name = model.Name,
                    Position = model.Position,
                    CreatedByUserId = (int)HttpContext.Session.GetInt32("CurrentUserId"),
                    StoreId = id
                };

                _context.Isles.Add(newIsle);
                _context.SaveChanges();
                newIsle = _context.Isles.Last();

                foreach(int catId in model.CategoryId){
                    IslesProductCategories newIPC = new IslesProductCategories{
                        ProductCategoryId = catId,
                        IsleId = newIsle.id
                    };
                    _context.IslesProductCategories.Add(newIPC);
                }

                _context.SaveChanges();


                return RedirectToAction("StoreDetails", "Store", new {id = id});

            }
            else{
                return View(model);
            }
        }

        [HttpPost]
        [Route("updateisle/{id}")]
        public IActionResult UpdateIsle(CreateIsleView model, int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            Isle currentIsle = _context.Isles.Where(isle => isle.id == id).Include(isle => isle.ProductCategories).ThenInclude(ipc => ipc.ProductCategory).SingleOrDefault();

            if(ModelState.IsValid){
                
                currentIsle.Name = model.Name;
                currentIsle.Position = model.Position;


                _context.Isles.Update(currentIsle);

                foreach(IslesProductCategories ipc in currentIsle.ProductCategories){
                    if(model.CategoryId.Contains(ipc.ProductCategoryId)){
                        model.CategoryId.Remove(ipc.ProductCategoryId);
                    }
                    else{
                        _context.IslesProductCategories.Remove(ipc);
                    } 
                }

                foreach(int catId in model.CategoryId){
                    IslesProductCategories newIPC = new IslesProductCategories{
                        ProductCategoryId = catId,
                        IsleId = currentIsle.id
                    };
                    _context.IslesProductCategories.Add(newIPC);
                }

                _context.SaveChanges();


                return RedirectToAction("StoreDetails", "Store", new {id = currentIsle.StoreId});

            }
            else{
                ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");
                ViewBag.Categories = _context.ProductCategories;
                ViewBag.Isle = currentIsle;

                return View(model);
            }
        }

    }
}

Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Identity;

using GroceryDash.Models;

namespace GroceryDash.Controllers
{
    public class StoreController : Controller
    {
        private GroceryDashContext _context;

        public StoreController(GroceryDashContext context){
            _context = context;
        }

        // GET: /Home/
        [HttpGet]
        [Route("createstore")]
        public IActionResult CreateStore()
        {
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            return View();
        }

        [HttpPost]
        [Route("createstore")]
        public IActionResult CreateStore(CreateStoreView model){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            if(ModelState.IsValid){
                Store newStore = new Store{
                    Name = model.Name,
                    Address1 = model.Address1,
                    Address2 = model.Address2,
                    City = model.City,
                    State = model.State,
                    Zip = model.Zip,
                    Description = model.Description,
                    CreatedByUserId = (int)HttpContext.Session.GetInt32("CurrentUserId")
                };

                _context.Stores.Add(newStore);
                _context.SaveChanges();
                newStore = _context.Stores.Last();


                return RedirectToAction("StoreDetails", new {id = newStore.id});

            }
            else{
                return View(model);
            }
        }

        [HttpGet]
        [Route("stores")]
        public IActionResult Stores(){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Stores = _context.Stores;

            return View();
        }


        [HttpGet]
        [Route("storedetails/{id}")]
        public IActionResult StoreDetails(int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Store = _context.Stores.Where(s => s.id == id).Include(s => s.Isles).ThenInclude(i => i.ProductCategories).ThenInclude(pc => pc.ProductCategory).SingleOrDefault();

            return View();
        }

        [HttpGet]
        [Route("updatestore/{id}")]
        public IActionResult UpdateStore(int id){
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            Store currentStore = _context.Stores.SingleOrDefault(store => store.id == id);
            CreateStoreView storeViewModel = new CreateStoreView{
                Name = currentStore.Name,
                Address1 = currentStore.Address1,
                Address2 = currentStore.Address2,
                City = currentStore.City,
                State = currentStore.State,
                Zip = currentStore.Zip,
                Description = currentStore.Description
            };

            ViewBag.StoreId = id;
            return View(storeViewModel);
        }

        [HttpPost]
        [Route("updatestore/{id}")]
        public IActionResult UpdateStore(CreateStoreView model, int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }
            if(ModelState.IsValid){
                Store currentStore = _context.Stores.SingleOrDefault(store => store.id == id);

                currentStore.Name = model.Name;
                currentStore.Address1 = model.Address1;
                currentStore.Address2 = model.Address2;
                currentStore.City = model.City;
                currentStore.State = model.State;
                currentStore.Zip = model.Zip;
                currentStore.Description = model.Description;
                currentStore.updated_at = DateTime.Now;

                _context.Stores.Update(currentStore);
                _context.SaveChanges();
                return RedirectToAction("StoreDetails", new {id = id});
            }
            else{
                ViewBag.StoreId = id;
                return View(model);
            }
            
        }

    }
}

Views/Store/CreateStore.cshtml
@{
    ViewData["Title"] = "Create New Store";
}

@using GroceryDash.Models

@model GroceryDash.Models.CreateStoreView

<h3>Create New Store</h3>

    <form asp-controller="Store" asp-action="CreateStore" method="POST">
    

        
        <p><span asp-validation-for="Name"></span>
        <label asp-for="Name"></label>
        <input asp-for="Name"></p>

        <p><span asp-validation-for="Address1"></span>
        <label asp-for="Address1"></label>
        <input asp-for="Address1"></p>

        <p><span asp-validation-for="Address2"></span>
        <label asp-for="Address2"></label>
        <input asp-for="Address2"></p>

        <p><span asp-validation-for="City"></span>
        <label asp-for="City"></label>
        <input asp-for="City"></p>

        <p><span asp-validation-for="State"></span>
        <label asp-for="State"></label>
        <input asp-for="State"></p>

        <p><span asp-validation-for="Zip"></span>
        <label asp-for="Zip"></label>
        <input asp-for="Zip"></p>

        <p><span asp-validation-for="Description"></span>
        <label asp-for="Description"></label>
        <textarea asp-for="Description"></textarea></p>

        
        <p><button class="big-button" type="submit" value="Create Store">Create Store</button></p>
    
    </form>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>

Views/Store/StoreDetails.cshtml
@{
    ViewData["Title"] = "Store Details";
}

@using GroceryDash.Models

<h3>@ViewBag.Store.Name</h3>

@if(@ViewBag.Store.Isles != null){
    @foreach(Isle isle in ViewBag.Store.Isles){
        string seperator = ", ";
        int i = 1;
        <h4>Isle @isle.Position - @isle.Name <a asp-controller="Isle" asp-action="UpdateIsle" asp-route-id="@isle.id"><button>Edit</button></a></h4>
        <h5>@foreach(IslesProductCategories cat in isle.ProductCategories){
               @cat.ProductCategory.Name
               if(i < isle.ProductCategories.Count){
                   @seperator
                }
                i++;
            }
        </h5>
    }
}

<a asp-controller="Isle" asp-action="CreateIsle" asp-route-id="@ViewBag.Store.id"><button class="big-button">Add Isle</button></a>
<a asp-controller="Store" asp-action="UpdateStore" asp-route-id="@ViewBag.Store.id"><button class="big-button">Edit Store Details</button></a>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>

Views/Store/Stores.cshtml
@{
    ViewData["Title"] = "Stores";
}

@using GroceryDash.Models

@if(ViewBag.Stores != null){
    @foreach(Store store in ViewBag.Stores){
        <p><a asp-controller="Store" asp-action="StoreDetails" asp-route-id="@store.id">@store.Name</a></p>
    }
}

Views/Store/UpdateStore.cshtml
@{
    ViewData["Title"] = "Create New Store";
}

@using GroceryDash.Models

@model GroceryDash.Models.CreateStoreView
<h3>Update Store</h3>

    <form asp-controller="Store" asp-action="UpdateStore" asp-route-id="@ViewBag.StoreId" method="POST">
    

        
        <p><span asp-validation-for="Name"></span>
        <label asp-for="Name"></label>
        <input asp-for="Name"></p>

        <p><span asp-validation-for="Address1"></span>
        <label asp-for="Address1"></label>
        <input asp-for="Address1"></p>

        <p><span asp-validation-for="Address2"></span>
        <label asp-for="Address2"></label>
        <input asp-for="Address2"></p>

        <p><span asp-validation-for="City"></span>
        <label asp-for="City"></label>
        <input asp-for="City"></p>

        <p><span asp-validation-for="State"></span>
        <label asp-for="State"></label>
        <input asp-for="State"></p>

        <p><span asp-validation-for="Zip"></span>
        <label asp-for="Zip"></label>
        <input asp-for="Zip"></p>

        <p><span asp-validation-for="Description"></span>
        <label asp-for="Description"></label>
        <textarea asp-for="Description"></textarea></p>

        
        <button class="big-button" type="submit" value="Update Store">Update Store</button>
    
    </form>

<a asp-controller="Store" asp-action="StoreDetails" asp-route-id="@ViewBag.StoreId"><button class="big-button">Back to Store</button></a>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>