Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Identity;

using GroceryDash.Models;

namespace GroceryDash.Controllers
{
    public class ProductController : Controller
    {
        private GroceryDashContext _context;

        public ProductController(GroceryDashContext context){
            _context = context;
        }

        // GET: /Home/
        [HttpGet]
        [Route("createproduct")]
        public IActionResult CreateProduct()
        {
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Categories = _context.ProductCategories;

            return View();
        }

        [HttpPost]
        [Route("createproduct")]
        public IActionResult CreateProduct(CreateProductView model){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            ViewBag.Categories = _context.ProductCategories;

            if(ModelState.IsValid){
                Product newProduct = new Product{
                    Name = model.Name,
                    Description = model.Description,
                    CreatedByUserId = (int)HttpContext.Session.GetInt32("CurrentUserId")
                };

                _context.Products.Add(newProduct);
                _context.SaveChanges();
                newProduct = _context.Products.Last();

                foreach(int catId in model.CategoryId){
                    ProductsProductCategories newPPC = new ProductsProductCategories{
                        ProductCategoryId = catId,
                        ProductId = newProduct.id
                    };
                    _context.ProductsProductCategories.Add(newPPC);
                }

                _context.SaveChanges();


                return RedirectToAction("Dashboard", "ShoppingList");

            }
            else{
                return View(model);
            }
        }

    }
}

Controllers/ShoppingListController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Identity;

using GroceryDash.Models;

namespace GroceryDash.Controllers
{
    public class ShoppingListController : Controller
    {
        private GroceryDashContext _context;

        public ShoppingListController(GroceryDashContext context){
            _context = context;
        }

       [HttpGet]
       [Route("dashboard")]
       public IActionResult Dashboard(){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.FullUser = _context.Users.Where(user => user.id == HttpContext.Session.GetInt32("CurrentUserId")).Include(user => user.MyShoppingLists).ThenInclude(slist => slist.ShoppingList).SingleOrDefault();

           return View();
       }

       [HttpGet]
       [Route("createlist")]
       public IActionResult CreateList(){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           return View();
       }

       [HttpPost]
       [Route("createlist")]
       public IActionResult CreateList(CreateShoppingListView model){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           if(ModelState.IsValid){
               ShoppingList newList = new ShoppingList{
                   Name = model.Name,
                   Permanent = model.Permanent
               };

               _context.ShoppingLists.Add(newList);
               _context.SaveChanges();

               newList = _context.ShoppingLists.Last();

               UsersShoppingLists listConnect = new UsersShoppingLists{
                   UserId = (int)HttpContext.Session.GetInt32("CurrentUserId"),
                    ShoppingListId = newList.id,
                    Access = 3
               };

               _context.UsersShoppingLists.Add(listConnect);
               _context.SaveChanges();

                return RedirectToAction("ListDetails", new {id = newList.id});
           }
           else{
               return View(model);
           }
           
       }

       [HttpGet]
       [Route("listdetails/{id}")]
       public IActionResult ListDetails(int id){
           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           ShoppingList currentList = _context.ShoppingLists.Where(sl => sl.id == id).Include(sl => sl.ShoppingListUsers).Include(sl => sl.Products).ThenInclude(p => p.Product).SingleOrDefault();

           UsersShoppingLists myConnection = currentList.ShoppingListUsers.SingleOrDefault(su => su.UserId == HttpContext.Session.GetInt32("CurrentUserId"));

           if(myConnection == null){
               return RedirectToAction("Dashboard");
           }

            ViewBag.Access = myConnection.Access;

            ViewBag.CurrentList = currentList;

            ViewBag.AllProducts = _context.Products;

           return View();
       }

       [HttpGet]
       [Route("removefromlist/{id}")]
       public IActionResult RemoveFromList(int id){
           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ShoppingListsProducts product = _context.ShoppingListsProducts.SingleOrDefault(slp => slp.id == id);
           int listId = product.ShoppingListId;

           _context.ShoppingListsProducts.Remove(product);
           _context.SaveChanges();

           return RedirectToAction("ListDetails", new {id = listId});
       }

       [HttpPost]
       [Route("addtolist")]
       public IActionResult AddToList(int productId, int repeat, int listId){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           if(productId > 0){
               ShoppingListsProducts toAdd = new ShoppingListsProducts{
                   ShoppingListId = listId,
                   ProductId = productId,
                   Repeat = repeat,
               };

               _context.ShoppingListsProducts.Add(toAdd);
               _context.SaveChanges();
           }

           

           return RedirectToAction("ListDetails", new {id = listId});
       }

       [HttpGet]
       [Route("goshopping/{listId}")]
       public IActionResult GoShopping(int listId){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           ViewBag.Stores = _context.Stores;
           ViewBag.ShoppingList = _context.ShoppingLists.SingleOrDefault(sl => sl.id == listId);

           return View();
       }

       [HttpPost]
       [Route("goshopping/{listId}")]
       public IActionResult GoShopping(int listId, int storeId){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           TempData["listId"] = listId;
           TempData["storeId"] = storeId;

           return RedirectToAction("ShoppingTrip");
       }

       [HttpGet]
       [Route("shoppingtrip")]
       public IActionResult ShoppingTrip(){

           if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           if(TempData["listId"] == null || TempData["storeId"] == null){
               return RedirectToAction("Dashboard");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

           int storeId = (int)TempData["storeId"];
           int listId = (int)TempData["listId"];

           Store store = _context.Stores.Where(s => s.id == storeId).Include(s => s.Isles).ThenInclude(i => i.ProductCategories).ThenInclude(pc => pc.ProductCategory).ThenInclude(pc => pc.Products).ThenInclude(ppc => ppc.Product).SingleOrDefault();

            store.Isles.Sort((i1, i2) => i1.Position.CompareTo(i2.Position));

           ShoppingList sList = _context.ShoppingLists.Where(sl => sl.id == listId).Include(sl => sl.ShoppingListUsers).Include(sl => sl.Products).ThenInclude(slp => slp.Product).ThenInclude(p => p.ProductCategories).SingleOrDefault();

           List<IsleProducts> isles = new List<IsleProducts>();

           foreach(Isle isle in store.Isles){
               IsleProducts ip = new IsleProducts(isle);
               List<Product> inventory = new List<Product>();

               foreach(IslesProductCategories cat in ip.ProductCategories){
                   foreach(ProductsProductCategories product in cat.ProductCategory.Products){
                       inventory.Add(product.Product);
                   } 
               }
               foreach(ShoppingListsProducts product in sList.Products){
                   if(inventory.Contains(product.Product)){
                       if(product.RepeatAfter < DateTime.Now){
                           ip.Products.Add(product.Product);
                       } 
                   };
               }
                if(ip.Products.Count > 0){
                    isles.Add(ip);
                }
           }

           ViewBag.Store = store;
           ViewBag.ShoppingList = sList;
           ViewBag.Isles = isles;

           return View();
       }

       [HttpGet]
       [Route("markcomplete/{id}")]
        public IActionResult MarkComplete(int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ShoppingList thisList = _context.ShoppingLists.SingleOrDefault(sl => sl.id == id);

           System.Console.WriteLine(" ");
            System.Console.WriteLine(thisList.Name);
            System.Console.WriteLine(thisList.Permanent);
           System.Console.WriteLine(" ");

           if(thisList.Permanent == 0){
               IEnumerable<UsersShoppingLists> usls = _context.UsersShoppingLists.Where(usl => usl.ShoppingListId == id);
                IEnumerable<ShoppingListsProducts> slps = _context.ShoppingListsProducts.Where(slp => slp.ShoppingListId == id);

                foreach(UsersShoppingLists usl in usls){
                    _context.UsersShoppingLists.Remove(usl);
                }

                foreach(ShoppingListsProducts slp in slps){
                    _context.ShoppingListsProducts.Remove(slp);
                }

                _context.ShoppingLists.Remove(thisList);

           }
           else{
               IEnumerable<ShoppingListsProducts> slps = _context.ShoppingListsProducts.Where(slp => slp.ShoppingListId == id);

               foreach(ShoppingListsProducts slp in slps){
                   if(slp.Repeat == 0){
                       _context.ShoppingListsProducts.Remove(slp);
                   }
                   else if(slp.Repeat == 2 && slp.RepeatAfter < DateTime.Now){
                       slp.RepeatAfter = slp.RepeatAfter.AddDays(7);
                       _context.ShoppingListsProducts.Update(slp);
                   }

Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Identity;

using GroceryDash.Models;

namespace GroceryDash.Controllers
{
    public class StoreController : Controller
    {
        private GroceryDashContext _context;

        public StoreController(GroceryDashContext context){
            _context = context;
        }

        // GET: /Home/
        [HttpGet]
        [Route("createstore")]
        public IActionResult CreateStore()
        {
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            return View();
        }

        [HttpPost]
        [Route("createstore")]
        public IActionResult CreateStore(CreateStoreView model){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            if(ModelState.IsValid){
                Store newStore = new Store{
                    Name = model.Name,
                    Address1 = model.Address1,
                    Address2 = model.Address2,
                    City = model.City,
                    State = model.State,
                    Zip = model.Zip,
                    Description = model.Description,
                    CreatedByUserId = (int)HttpContext.Session.GetInt32("CurrentUserId")
                };

                _context.Stores.Add(newStore);
                _context.SaveChanges();
                newStore = _context.Stores.Last();


                return RedirectToAction("StoreDetails", new {id = newStore.id});

            }
            else{
                return View(model);
            }
        }

        [HttpGet]
        [Route("stores")]
        public IActionResult Stores(){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Stores = _context.Stores;

            return View();
        }


        [HttpGet]
        [Route("storedetails/{id}")]
        public IActionResult StoreDetails(int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

           ViewBag.CurrentUserFirstName = HttpContext.Session.GetString("CurrentUserFirstName");

            ViewBag.Store = _context.Stores.Where(s => s.id == id).Include(s => s.Isles).ThenInclude(i => i.ProductCategories).ThenInclude(pc => pc.ProductCategory).SingleOrDefault();

            return View();
        }

        [HttpGet]
        [Route("updatestore/{id}")]
        public IActionResult UpdateStore(int id){
            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }

            Store currentStore = _context.Stores.SingleOrDefault(store => store.id == id);
            CreateStoreView storeViewModel = new CreateStoreView{
                Name = currentStore.Name,
                Address1 = currentStore.Address1,
                Address2 = currentStore.Address2,
                City = currentStore.City,
                State = currentStore.State,
                Zip = currentStore.Zip,
                Description = currentStore.Description
            };

            ViewBag.StoreId = id;
            return View(storeViewModel);
        }

        [HttpPost]
        [Route("updatestore/{id}")]
        public IActionResult UpdateStore(CreateStoreView model, int id){

            if(HttpContext.Session.GetString("CurrentUserFirstName") == null){
               return RedirectToAction("Index", "Home");
           }
            if(ModelState.IsValid){
                Store currentStore = _context.Stores.SingleOrDefault(store => store.id == id);

                currentStore.Name = model.Name;
                currentStore.Address1 = model.Address1;
                currentStore.Address2 = model.Address2;
                currentStore.City = model.City;
                currentStore.State = model.State;
                currentStore.Zip = model.Zip;
                currentStore.Description = model.Description;
                currentStore.updated_at = DateTime.Now;

                _context.Stores.Update(currentStore);
                _context.SaveChanges();
                return RedirectToAction("StoreDetails", new {id = id});
            }
            else{
                ViewBag.StoreId = id;
                return View(model);
            }
            
        }

    }
}

Views/ShoppingList/CreateList.cshtml
@{
    ViewData["Title"] = "Create New Shopping List";
}

@model GroceryDash.Models.CreateShoppingListView

<form asp-controller="ShoppingList" asp-action="CreateList" method="POST">
    <p><span asp-validation-for="Name"></span>
    <label asp-for="Name"></label>
    <input asp-for="Name" placeholder="List Name"></p>
    
    <p><span asp-validation-for="Permanent"></span>
    <select asp-for="Permanent">
        <option value="1">Permanent</option>
        <option value="0">One-Time Use</option>
        </select></p>

    <button class="big-button" type="submit">Create New List</button>
</form>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>

Views/ShoppingList/Dashboard.cshtml
@{
    ViewData["Title"] = "Welcome to Grocery Dash!";
}

@using GroceryDash.Models

<h3>Welcome, @ViewBag.CurrentUserFirstName</h3>

@{
    User user = (User)ViewBag.FullUser;
    @if(@user.MyShoppingLists.Count > 0){
    
        @foreach(var list in user.MyShoppingLists){
            <p>@list.ShoppingList.Name <a asp-controller="ShoppingList" asp-action="ListDetails" asp-route-id="@list.ShoppingList.id"><button>Edit</button></a> <a asp-controller="ShoppingList" asp-action="GoShopping" asp-route-listId="@list.ShoppingList.id"><button>Go Shopping</button></a></p>
        }
    }
}

<a asp-controller="ShoppingList" asp-action="CreateList"><button class="big-button">Build New List</button></a>

<a asp-controller="Product" asp-action="CreateProduct"><button class="big-button">Add New Product</button></a>

<a asp-controller="ProductCategory" asp-action="CreateProductCategory"><button class="big-button">Add New Product Category</button></a>

<a asp-controller="Store" asp-action="CreateStore"><button class="big-button">Add New Store</button></a>

<a asp-controller="Store" asp-action="Stores"><button class="big-button">View All Stores</button></a>

Views/ShoppingList/GoShopping.cshtml
@{
    ViewData["Title"] = "Let's Go Shopping";
}

@using GroceryDash.Models

@if(@ViewBag.ShoppingList != null){
    <h3>@ViewBag.ShoppingList.Name</h3>

    <form asp-controller="ShoppingList" asp-action="GoShopping" asp-route-listId="@ViewBag.ShoppingList.id" method="POST">
        <select name="storeId">
            @if(@ViewBag.Stores != null){
                @foreach(Store store in @ViewBag.Stores){
                    <option value="@store.id">@store.Name</option>
                }
            }
        </select>

        <input type="submit" value="Choose Store">
    </form>
}

<a asp-controller="Store" asp-action="CreateStore"><button class="big-button">Add New Store</button></a>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>

Views/ShoppingList/ListDetails.cshtml
@{
    ViewData["Title"] = "Edit Shopping List";
}

@using GroceryDash.Models

@if(ViewBag.CurrentList != null){
    <h3>@ViewBag.CurrentList.Name</h3>

    @foreach(ShoppingListsProducts product in @ViewBag.CurrentList.Products){
        <p>@product.Product.Name <a asp-controller="ShoppingList" asp-action="RemoveFromList" asp-route-id="@product.id"><button>Remove</button></a></p>
    }
}

<form asp-controller="ShoppingList" asp-action="AddToList" method="POST">
    <p>
        <select name="productId">
            <option value="0">Available Products</option>
            @if(@ViewBag.AllProducts != null){
                @foreach(Product product in @ViewBag.AllProducts){
                    <option value="@product.id">@product.Name</option>
                }
            }
            
        </select>
        <select name="repeat">
            <option value="0">Do Not Repeat</option>
            <option value="1">Repeat Weekly</option>
            <option value="2">Repeat Bi-Weekly</option>
            <option value="3">Repeat Monthly</option>
        </select>
        <input type="hidden" name="listId" value="@ViewBag.CurrentList.id">
        <input type="submit" value="Add Product">
    </p>
</form>

<a asp-controller="ShoppingList" asp-action="GoShopping" asp-route-listId="@ViewBag.CurrentList.id"><button class="big-button">Go Shopping</button></a>

<a asp-controller="Product" asp-action="CreateProduct"><button class="big-button">Add New Product</button></a>

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>

Views/ShoppingList/ShoppingTrip.cshtml
@{
    ViewData["Title"] = "Shopping Trip";
}

@using GroceryDash.Models

@if(@ViewBag.ShoppingList != null && @ViewBag.Store != null && @ViewBag.Isles != null){
    <h3>@ViewBag.ShoppingList.Name - @ViewBag.Store.Name</h3>

   
    @foreach(IsleProducts isle in ViewBag.Isles){

        string seperator = ", ";
        int i = 1;

        <h4>Isle @isle.Position - @isle.Name</h4>

        <h5>@foreach(IslesProductCategories cat in isle.ProductCategories){
               @cat.ProductCategory.Name
               if(i < isle.ProductCategories.Count){
                   @seperator
                }
                i++;
            }
        </h5>
        
        <ul class="shopping-trip-list">

            @foreach(Product product in isle.Products){
                <li><input class="trip-checkbox" type="checkbox">@product.Name</li>
            }
        </ul>
        
    }

    <a asp-controller="ShoppingList" asp-action="MarkComplete" asp-route-id="@ViewBag.ShoppingList.id"><button class="big-button">Mark Trip Complete</button></a>
}

<a asp-controller="ShoppingList" asp-action="Dashboard"><button class="big-button">Back To Dashboard</button></a>